# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: "eu-north-1"
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_PROD_JOB_PATH: ${{secrets.AWS_PROD_JOB_PATH}}
  AWS_DEV_JOB_PATH: ${{secrets.AWS_DEV_JOB_PATH}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: export aws values
        run: |
          export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
          export AWS_REGION="$AWS_REGION"
      - name: deploy s3 script
        run: |
          aws s3 sync prod_preprocess_data/ "$AWS_PROD_JOB_PATH"/prod_preprocess_data/
          aws s3 sync prod_validate_data/ "$AWS_PROD_JOB_PATH"/prod_validate_data/
          aws s3 sync prod_aggregate_data/ "$AWS_PROD_JOB_PATH"/prod_aggregate_data/
          aws s3 sync prod_load_data/ "$AWS_PROD_JOB_PATH"/prod_load_data/